title: "Monads in Scala"
email: andreas.faltermaier@gmail.com
description: "Monads in Scala"
baseurl: "https://anfalt.github.io/MonadsInScala"
url: "https://anfalt.github.io/MonadsInScala"
exclude: ["LICENSE", "Remarks.md"]
github_username: ["anfalt"]

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: jekyll-theme-cayman
